import Layout from "../../../src/components/dashboard/Layout";
import Student from "../../../src/components/dashboard/Student";
import Head from "next/head";
import axios from "axios";
import { useState, useEffect } from "react";
export default function Students() {
  const [student, setStudent] = useState([]);
  const loadStudent = async () => {
    let data = await axios.get("/api/student", []);
    setStudent(data.data);
  };
  useEffect(() => {
    loadStudent();
  }, [student]);
  return (
    <div>
      <Head>
        <title>Сурагчид</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo/lil_logo.png" />
      </Head>
      <div className="flex overflow-hidden h-screen">
        <div className="admin_sidebar">
          <Layout />
        </div>
        <div className="admin_dashboard">
          <Student data={student} />
        </div>
      </div>
    </div>
  );
}
