import Head from "next/head";
import Layout from "../../../src/components/dashboard/Layout";
import Lesson from "../../../src/components/dashboard/Lesson";
export default function Lessons() {
  return (
    <div>
      <Head>
        <title>Хичээл</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo/lil_logo.png" />
      </Head>
      <div className="flex overflow-hidden h-screen">
        <div className="admin_sidebar">
          <Layout />
        </div>
        <div className="admin_dashboard">
          <Lesson />
        </div>
      </div>
    </div>
  );
}
