import Layout from "../../../src/components/dashboard/Layout";
import Teacher from "../../../src/components/dashboard/Teacher";
import Head from "next/head";
export default function Teachers() {
  return (
    <>
      <Head>
        <title>Багш нар</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo/lil_logo.png" />
      </Head>
      <div className="flex">
        <div className="admin_sidebar">
          <Layout />
        </div>
        <div className="admin_dashboard">
          <Teacher />
        </div>
      </div>
    </>
  );
}
