import axios from "axios";
import Head from "next/head";

import Login from "./signin";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Монголын цогц сургалтын төв</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./img/logo/lil_logo.png" />
      </Head>
      <Login />
    </div>
  );
}
