import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import Sidebar from "../src/components/auth/Sidebar";
import Navbar from "../src/components/Navbar";
import { Alert } from "@mui/material";
import axios from "axios";
export default function Logup() {
  const [user, setUser] = useState();
  const [error, setError] = useState();
  const [username, setUsername] = useState("");
  const [repeatPassword, setRepeatPassword] = useState("");
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const router = useRouter();
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    const credentials = { username, email, password };
    const user = await axios.post("/api/auth/logup", credentials);
    setMessage(user.data.message);
  };
  if (message == "success") {
    router.push("/login");
  }
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./img/logo/lil_logo.png" />
        <title>Бүртгүүлэх</title>
      </Head>
      {!user && (
        <div className="flex relative">
          <Sidebar />
          <div className="auth w-1/3">
            <Navbar data="logup" />
            <div className="sign">
              {error && (
                <Alert variant="outlined" severity="info" className="mb-10">
                  {error}
                </Alert>
              )}
              <form action="" onSubmit={handleSubmit}>
                <h2 className="font-bold text-4xl mb-6">Бүртгүүлэх</h2>
                <input
                  type="text"
                  name="username"
                  placeholder="Овог, нэр"
                  id="username"
                  onChange={(e) => setUsername(e.target.value)}
                  className="w-full rounded-md border-gray-200 px-3 py-2 border-solid border mb-4"
                />
                <input
                  type="text"
                  name="email"
                  placeholder="И-Майл"
                  id="email"
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full rounded-md border-gray-200 px-3 py-2 border-solid border mb-4"
                />
                <input
                  type="password"
                  name="password"
                  id="password"
                  placeholder="Нууц үгээ оруулна уу"
                  className="w-full rounded-md border-gray-200 px-3 py-2 border-solid border mb-4"
                  onChange={(e) => setPassword(e.target.value)}
                />
                <input
                  type="password"
                  name="repeat_password"
                  id="repeat_password"
                  placeholder="Нууц үгээ дахин оруулна уу"
                  className="w-full rounded-md border-gray-200 px-3 py-2 border-solid border mb-4"
                  onChange={(e) => setRepeatPassword(e.target.value)}
                />

                <button className="w-full rounded-md font-semibold px-3 py-3 bg text-white mb-4">
                  Бүртгүүлэх
                </button>
              </form>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
